### ISSUE TITLE
Multiple Datasources issue

### ISSUE THREAD

**Issue by KoloritnijClap** [grails/gorm-graphql#13]
There is some problems to work with multiple datasources(for example MySQL and MongoDB). I've made local fix that plugin generate schema for both datasources. But there is an big work to add return type from one datasources to another. Are you working on it or maybe I should make a pull request?

**Comment by jameskleeh** [comment]
The library now works with multiple datasource types, however will only use the default connection in each

**Comment by KoloritnijClap** [comment]
I'm using 1.0.0.RC2 version(that latest in the docs) and it generate schema only from default Datasource(for me it's Hibernate), but I want that it generate from Mongo as well too.

**Comment by jameskleeh** [comment]
@KoloritnijClap If you use `1.0.0.BUILD-SNAPSHOT` now, or the next release, it will generate for Mongo as well
