### ISSUE TITLE
Custom Operations registered using EntityDataFetcher do not accept standard arguments

### ISSUE THREAD

**Issue by kdpeders** [grails/gorm-graphql#16]
query('authorList', [Author]) {
      dataFetcher(new EntityDataFetcher<List<Author>>(Author.gormPersistentEntity) {
        @Override
        protected DetachedCriteria buildCriteria(DataFetchingEnvironment environment) { 
          Author.where {name != 'King'}
        }
      })
    }

Results in schema of:

     authorList: [Author]

rather than:

     authorList(
     max: Int
     offset: Int
     sort: String
     order: String
     ignoreCase: Boolean
     ): [Author]

**Comment by jameskleeh** [comment]
This is working as designed. That being said it isn't unreasonable to have a feature that would allow you to use those list arguments. I'll see what I can come up with

**Comment by jameskleeh** [comment]
@kdpeders Try out the latest snapshot

https://github.com/grails/gorm-graphql/commit/e87330d16d2285e34b47512f0a295704606406ed

**Comment by kdpeders** [comment]
That worked thanks!

    query('authorList', [Author]) {
      defaultListArguments()
      dataFetcher(new EntityDataFetcher<List<Author>>(Author.gormPersistentEntity) {
        @Override
        protected DetachedCriteria buildCriteria(DataFetchingEnvironment environment) { 
          Author.where {name != 'King'}
        }
      })
    }

Now results in:

    authorList(
     max: Int
     offset: Int
     sort: String
     order: String
     ignoreCase: Boolean
     ): [Author]

**Comment by kdpeders** [comment]
Any chance you can tag a release with this fix?
