### ISSUE TITLE
There is no GrailsGraphQLDataBinder in Standalone Projects, and Nested properties will not be set

### ISSUE THREAD

**Issue by neoscript99** [grails/gorm-graphql#18]
# my code
- url: https://github.com/neoscript99/gorm-graphql-spring-boot
- It's Standalone spring boot project, do not use grails, instead use `com.graphql-java:graphql-spring-boot-starter:3.9.2` for graphQLServlet
- [my AutoConfigure](https://github.com/neoscript99/gorm-graphql-spring-boot/blob/master/gorm-graphql-spring-boot-starter/src/main/groovy/neo/script/gorm/graphql/GormGraphqlSpringBootAutoConfiguration.groovy)
# Problem
## when I create Talk(as same as example project):
- speaker with given id is exist
```
mutation {
  talkCreate(talk: {title: "new talk", duration: 20, speaker: {id: "6bd39acb-c4b6-46b2-a564-5779d75cee2d"}}) {
    id
    title
    duration
    errors {
      field
      message
    }
  }
}

``` 

## return error
```
{
  "data": {
    "talkCreate": {
      "id": null,
      "title": "new talk",
      "duration": 20,
      "errors": [
        {
          "field": "speaker",
          "message": "Property [speaker] of class [class neo.script.gorm.graphql.demo.domain.Talk] cannot be null"
        }
      ]
    }
  }
}
```
# my analyze
1. Without `org.grails.gorm.graphql.plugin.binding.GrailsGraphQLDataBinder`, `speaker(id:1)` do not set for Talk.

Will you solve this problem?

**Comment by benlucchesi** [comment]
I'm experiencing the same problem. I'm using this library with micronaut and its just not as fun as I expected it to be....

My current solution is to hack data mapping into place with garbage code like this to perform a nested create.

```
  GraphQLDataBinderManager dataBinderManager = schema.dataBinderManager
  dataBinderManager.registerDataBinder(Author, new GraphQLDataBinder() {
        @Override
        void bind(Object object, Map data) {
           Author author = (Author) object
           data.books.each{ author.addToBooks( new Book( it ) ) }
        }   
 })

```

**Comment by jameskleeh** [comment]
It's outside the scope of the core library to provide a data binding function.  You should use whatever data binding mechanism is already in place for whatever framework you're using. 

@benlucchesi There is a gorm-graphql library specifically for micronaut that includes a data binder https://github.com/micronaut-projects/micronaut-groovy/blob/master/graphql-gorm/src/main/groovy/io/micronaut/configuration/graphql/gorm/DefaultGraphQLDataBinder.groovy
