### ISSUE TITLE
Additional filtering parameters when adding a custom property to a domain class

### ISSUE THREAD

**Issue by vasilevichra** [grails/gorm-graphql#25]
Hi!

I have class `Foo` with custom property `bar`.

```groovy
 class Foo {
     static graphql = GraphQLMapping.build {
         add('bar', Bar) {
             dataFetcher { Foo foo, ClosureDataFetchingEnvironment env ->
                 //The fetchArguments will be populated based on what properties
                 //were requested from the 'bar'
                 Bar.where { .list(env.fetchArguments)
             }
         }
     }
 }
 }
```
like in this example https://grails.github.io/gorm-graphql/snapshot/api/org/grails/gorm/graphql/fetcher/impl/ClosureDataFetchingEnvironment.html

And domain class `Bar` contains property `baz`. So I try to filter by this parameter `baz`
```js
{
  foo(id: 1000) {
    id
    bar (baz: "bla") {
      id
    }
  }
}
```
but I'm getting an error: `Validation error of type UnknownArgument: Unknown field argument baz`
What I'm doing wrong? Please help

**Comment by jameskleeh** [comment]
You can only accept arguments at the top level

```
{
  foo(id: 1000, baz: "bla") {
    id
    bar {
      id
    }
  }
}
```
