### ISSUE TITLE
Feature request: ability to reuse nested POGO on multiple domain classes without gql type DSL duplication

### ISSUE THREAD

**Issue by brdbry** [grails/gorm-graphql#26]
I have a class with multiple layers of nesting that I would like to attach to the graphql queries for many domain classes (i.e. a good use-case for `add()`)

I didn't make this POGO a domain class, because the whole thing is read-only (no DB persistence) and built at query-time.

This means I need to declare my gql types manually instead of automatically by the plugin (fine), but I'm hoping to colocate the  gql type markup and properties on the nested classes, and keep my code DRY.

However, because of the nesting on the POGO, I couldn't find a way to make re-use of the whole class without declaring the full gql type markup on each domain class.

I have created a repo showing this: https://github.com/brdbry/gorm-graphql-nested-pogo

See the IncomingIntercoDrawdown and OutgoingIntercoDrawdown domain classes for an example.

Would it be possible to allow some way of achieving nesting POGOs in the plugin e.g. some GQL type name suffix parameter that can be passed in when defining the type at the top level?

Failing that, can you think of an alternative design pattern I could use instead?
Alternative solutions considered and failed already (though I may have done something wrong):

- Set a variable in the top level scope (like gqlTypeNameQualifier); but the closure resolution strategy for the closures are explicitly set to DELEGATE_ONLY by the plugin, removing the ability to read owner variables
- Make the nested class a domain class but switch off persistence (I tried this with `mapWith = 'none'` and it didn't work, but I just saw `isAttached()` approach here (https://stackoverflow.com/questions/3490135/do-grails-domain-classes-have-to-be-tied-to-a-database) so I'll try that too).
- Find and rename the types in LeafGraphQLSchemaInterceptor; but the GraphQLObjectType properties are read-only, and the GraphQLFieldDefinition.Builder only seems to allow top-down construction of a field hierarchy (not targeted swap-out)

Thanks in advance.

**Comment by brdbry** [comment]
Hi @jameskleeh Just wondering if you had chance to have a read of this?

**Comment by jameskleeh** [comment]
So you can achieve what you want by doing the following

Register an interceptor:
```
class GraphQLConfigurer extends GraphQLPostProcessor {

    GraphQLTypeManager graphQLTypeManager

    @Override
    void doWith(GraphQLInterceptorManager interceptorManager) {
        interceptorManager.registerInterceptor(new GraphQLSchemaInterceptor() {
            @Override
            void interceptEntity(PersistentEntity entity, List<GraphQLFieldDefinition.Builder> queryFields, List<GraphQLFieldDefinition.Builder> mutationFields) {

            }

            @Override
            void interceptSchema(GraphQLObjectType.Builder queryType, GraphQLObjectType.Builder mutationType, Set<GraphQLType> additionalTypes) {
                ComplexField workflowDetails = new ComplexField().typeName("EntityWorkflowDetails")
                workflowDetails.field('currentUserTask','EntityWorkflowTask', {
                            field('processInstanceId',String)
                            field('processDefinitionKey', String)
                            field('processName',String)
                            field('assigneeLogon',String)
                            field('assigneeFullName',String)
                            field('currentActivityId',String)
                            field('userTaskName',String)
                            field('progressionOptions','WorkflowTaskProgressionOption') {
                                field('nextActivityId',String)
                                field('actionName',String)
                                field('seqFlowId',String)
                                field('assigneeOptions','ProgressionOptionAssignee') {
                                    field('userLogonOrRole',String)
                                    field('userFullNameOrRoleName',String)
                                    field('assigneeType',String)
                                    collection true
                                }
                                field('commentIsRequired',Boolean)
                                collection true
                            }
                        })
                additionalTypes.add(workflowDetails.getType(graphQLTypeManager, null))
            }
        })
    }
}
```

Create a custom class to represent your property
```
class EntityWorkflowProperty extends CustomGraphQLProperty<EntityWorkflowProperty> {

    EntityWorkflowProperty(Closure dataFetcher) {
        this.closureDataFetcher = dataFetcher
        this.name = "workflow"
        this.input = false
    }

    @Override
    GraphQLType getGraphQLType(GraphQLTypeManager typeManager, GraphQLPropertyType propertyType) {
        return new GraphQLTypeReference("EntityWorkflowDetails")
    }
}
```

In both domains simply use the class:
```
    static graphql = GraphQLMapping.lazy {
        add(new EntityWorkflowProperty({
            IncomingIntercoDrawdown intercoDrawdown ->
                return new EntityWorkflowDetails() //real data fetcher builds POGO with all nested objects/properties populated
        }))
    }
```

**Comment by brdbry** [comment]
Thanks @jameskleeh ! This is just what I was looking for
