### ISSUE TITLE
Quoting keys in JSON argument of mutation

### ISSUE THREAD

**Issue by ianibo** [grails/gorm-graphql#30]
Heya. I've been pulling together a really trivial example project that demonstrates a custom operation on a grails 4.0.0 app - with the hope of submitting some doc improvements and suggesting we use this lib in a service. Demo/test project is here: https://github.com/ianibo/graphql_grails4_test. and you can recreate this case by checking that out; using grails (4.0.0) run-app and then running the script test_api.sh at the root of the project in a different shell. Had a few stumbles along the way but almost there now and having loads of fun. Just one real headache left: In my test script if I submit a mutation as follows:

    curl -X "POST" "http://localhost:8080/graphql" \
         -H "Content-Type: application/graphql" \
         -d $'
    mutation {
      widgetCreate(widget: {
        name: "AATestWidget",
        description: "AATestWidget Description"
      }) {
        id
        name
        description
        errors {
          field
          message
        }
      }
    }
    '

Everything works great - but in trying to use this code in a test harness, I'd like to generate the value of the widget argument using some other libraries. Specifically, I'd like to use groovy.json.JsonOutput to render a map as JSON and then use that JSON a the mutation parameter. The only problem is that groovy.json.JsonOutput insists on quoting it's keys, so what gets sent in this case is 

      mutation {
          widgetCreate(widget: {
            "name": "AATestWidget",
            "description": "AATestWidget Description"
          }) {
            id
            name
            description
            errors {
              field
              message
            }
          }
        }

Sending this, however, always results in 

{"data":null,"errors":[{"message":"Invalid Syntax : offending token '\"name\"' at line 4 column 5","errorType":"InvalidSyntax","locations":[{"line":4,"column":5}]}]}

In reading the docs at https://graphql.org/learn/queries/ it seems that it's OK for the content of the argument to be well-formed JSON. Is there any way to either enable sending a well-formed JSON parameter within the body of the argument or have I missed any more obvious way of achieving this (Or just misunderstood what is going on here)?

Cheers in advance,
Ian.

**Comment by jameskleeh** [comment]
You should use variables

See https://graphql.org/learn/serving-over-http/#post-request

**Comment by ianibo** [comment]
Yep, thanks - I was almost there myself - is there an example of the syntax anywhere? I can't quite seem to get it right - at the moment I have this:

     curl -X "POST" "http://localhost:8080/graphql" \
          -H "Content-Type: application/json" \
          -d $'{
       "query" : "mutation { widgetCreate(widget: $vw) { id name description errors { field message } } }",
       "variables": {
         "vw" : { "name": "AATestWidget", "description": "AATestWidget Description" }
       }
     }
    '

The examples use a Type in the mutation($vw TypeNameHere) but I'm not sure what that should be?

**Comment by jameskleeh** [comment]
Its whatever type the data is representing, probably `WidgetCreate` in your case

**Comment by ianibo** [comment]
Yep - you're exactly right. For anyone else finding this issue, the working final form was

    curl -X "POST" "http://localhost:8080/graphql"      
    -H "Content-Type: application/json"     
     -d $'{
      "query" : "mutation($vw: WidgetCreate) { widgetCreate(widget: $vw) { id name description errors { field message } } }",
      "variables": {
        "vw" : { "name": "AATestWidget", "description": "AATestWidget Description" }
      }
    }
    '

And obvs - find the type name using introspection:

    curl -X "POST" "http://localhost:8080/graphql" \
         -H "Content-Type: application/graphql" \
         -d $'{
      __schema {
        types {
          name
        }
      }
    }'

Thanks!
