### ISSUE TITLE
Add 'extension' to the response

### ISSUE THREAD

**Issue by kirpi4ik** [grails/gorm-graphql#34]
According to the [spec](https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md#response-format) graphql response is allowed to contain 'extension' node which is actually filtered out in [GraphqlController](https://github.com/grails/gorm-graphql/blob/master/plugin/grails-app/controllers/org/grails/gorm/graphql/plugin/GraphqlController.groovy#L65)

**Comment by puneetbehl** [comment]
@kirpi4ik I am not sure if I understand, the code you pointed out in GraphQLController does not filter out the extension from errors. Could you please create.a sample application?

**Comment by puneetbehl** [comment]
@kirpi4ik I got confused with the `extensions` entry under `errors`, sorry for the confusion.
