### ISSUE TITLE
Spring Security Core Not Working with Graphql

### ISSUE THREAD

**Issue by harishbabu18** [grails/gorm-graphql#50]
Role-Based Api and User-Based Filter is not working for graphql in grails.

**Comment by orr3** [comment]
FYI.
We use Gorm GraphQL + Spring security core + Spring security Rest + Multi tenancy feature of GORM 7.0.4 without any hassles.

We have a working role based interceptUrlMap and /graphql endpoint with joined filters.

compile "org.grails.plugins:gorm-graphql-plugin:2.0.1.BUILD-SNAPSHOT"
compile "org.grails.plugins:spring-security-rest:3.0.1"
compile "org.grails.plugins:spring-security-rest-gorm:3.0.1"

**Comment by harishbabu18** [comment]
can you give me an example with graphql.I am not able to implement interceptUrlMap properly

**Comment by jamesdh** [comment]
@harishbabu18 it's just an endpoint: `/graphql`

It can have its security configured just like any other endpoint via Spring Security.

**Comment by harishbabu18** [comment]
@jamesdh @jeffbrown @orr3 Let's assume I have a table. I want to show the list to everyone but edit and create for only creators.How can we do this. Interceptor takes care of URL /graphql but create and edit method.Please Guide me in this Aspect.

**Comment by orr3** [comment]
We've solved this with GraphQLFetcherInterceptor.
For each graphql enabled domain we register an interceptor that will check if current user holds required role and based on that we deny or allow further propagation. 

```
import grails.plugin.springsecurity.SpringSecurityUtils

@CompileStatic
class AdminAllowedDataFetcherInterceptor implements SecureDataFetcherInterceptor {

    String adminRole = "ROLE_ADMIN";
    
    // Highest prio
    int getOrder() {
        return 0;
    }

    boolean onQuery(DataFetchingEnvironment environment, GraphQLDataFetcherType type) {
        return SpringSecurityUtils.ifAnyGranted(adminRole)
    }

    boolean onMutation(DataFetchingEnvironment environment, GraphQLDataFetcherType type) {
        return SpringSecurityUtils.ifAnyGranted(adminRole)
    }

    boolean onCustomQuery(String name, DataFetchingEnvironment environment) {
        return SpringSecurityUtils.ifAnyGranted(adminRole)
    }

    boolean onCustomMutation(String name, DataFetchingEnvironment environment) {
        return SpringSecurityUtils.ifAnyGranted(adminRole)
    }
}
```

SecureDataFetcherInterceptor is our own interface extending GraphQLFetcherInterceptor and org.grails.datastore.mapping.core.Ordered.

For your example with securing  CREATE and EDIT mutation I would implement this logic in the `onMutation` and `onCustomMutation` depending on how you've implemented graphql in your Table domain.

```
boolean onMutation(DataFetchingEnvironment environment, GraphQLDataFetcherType type) {
        switch (type) {
            case GraphQLDataFetcherType.CREATE:
                // Check Spring Security role
                break
            case GraphQLDataFetcherType.UPDATE:
                // Check Spring Security role
                break
            case GraphQLDataFetcherType.DELETE:
                // Check Spring Security role
                break
            
            default:
                // Allow
                return true
        }
    }
```
