### ISSUE TITLE
No means for defining field arguments

### ISSUE THREAD

**Issue by jamesdh** [grails/gorm-graphql#53]
From the GraphQL spec:

> Every field on a GraphQL object type can have zero or more arguments, for example the length field below:

```
type Starship {
  id: ID!
  name: String!
  length(unit: LengthUnit = METER): Float
}
```

I was expecting there to be some way similar to defining query operations, a la...
```
query('authorByName', Author) {
    argument('name', String) 
    ...
}
```
but there doesn't appear to be any way to define arguments for fields.

The only workaround I can see is to define another query operation, but then you lose the context of the "source" (parent) object, and at that point it largely defeats the purpose of using GraphQL because you're having to make multiple queries to retrieve the same data that should otherwise be retrievable in a single query.

**Comment by jamesdh** [comment]
In essense, this is the type of query that should be supported. This is a very common use case:

```graphql
query {
  org(id: 123456) {
    id
    name
    trends(users: ['jamesdh']) {
      date
      quantity
    }
  }
}
```
What changes I believe the entity DSL needs:
- The `arguments` package is promoted from `entity/operations/arguments` to `entity/arguments` to make their use across the DSL clearer. 
- An `argument` clause is added for [CustomGraphQLProperty](https://github.com/grails/gorm-graphql/blob/4143ecd83f6e13f50f81a0e0354ceacde0ea1df2/core/src/main/groovy/org/grails/gorm/graphql/entity/property/impl/CustomGraphQLProperty.groovy)
- In the event that a DataFetcher is provided to the CustomGraphQLProperty, any arguments would be added to the ClosureDataFetchingEnvironment

Hence, I could do the following:
```groovy
class Org {
    String name

    static graphql = GraphQLMapping.build {
        add('trends', 'Trend') {
            argument('users', [String]) {
                defaultValue null
                nullable true
            }
            type {
                collection(true)
                field('date', Date)
                field('quantity', Integer)
            }
            dataFetcher { Org org, ClosureDataFetchingEnvironment env ->
                List<String> userIds = env.getArgument('users')
                Map context = (Map)env.context
                TrendService trendService = (TrendService)context.trendService
                trendService.getAllTrends(org.id, userIds)
            }
        }
    }
}
```

Extra Credit:
- In the event that the property is backed by a getter method, we allow the method to support arguments and we infer those arguments automatically during schema generation. 

Hence I could do the following:

```groovy
class Org {

    List<Trend> getTrends(List<String> users = null) {
        trendService.getAllTrends(this.id, userIds)
    }

    static graphql = GraphQLMapping.build {
        add('trends', 'Trend') {
            type {
                collection(true)
                field('date', Date)
                field('quantity', Integer)
            }
        }
    }
}
```

**Comment by jameskleeh** [comment]
@jamesdh I'm relatively certain this functionality wasn't part of the spec when this library was created. I agree we should be able to support this use case and the ideas you presented seem good from a broad strokes perspective. Are you interested in sending a PR with these changes?

**Comment by jamesdh** [comment]
@jameskleeh already working on it!
